# Generated by Django 5.0.1 on 2024-02-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(max_length=10)),
                ('volume', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('pharmacological_group', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer_country', models.CharField(max_length=30)),
                ('manufacturer_company', models.CharField(max_length=30)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('release_form', models.CharField(blank=True, max_length=100, null=True)),
                ('access_medicament', models.CharField(blank=True, max_length=12, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, max_length=100, null=True)),
                ('composition', models.TextField(blank=True, max_length=2000, null=True)),
                ('peculiarities', models.TextField(blank=True, max_length=2000, null=True)),
                ('product_packaging', models.TextField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('indications_for_use', models.TextField(blank=True, max_length=2000, null=True)),
                ('contraindications', models.TextField(blank=True, max_length=2000, null=True)),
                ('mode_of_application', models.TextField(blank=True, max_length=2000, null=True)),
                ('storage_conditions', models.TextField(blank=True, max_length=2000, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
