# Generated by Django 5.0.2 on 2024-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=100),
        ),
    ]
